name: Scrape Recent Releases

on:
  schedule:
    - cron: '0 * * * *'  # This cron expression schedules the job to run every hour
  workflow_dispatch:     # Allows manual triggering of the workflow from the GitHub UI

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get the public IP of this runner
      id: get_gh_runner_ip
      shell: bash
      run: |
        echo "ip_address=$(curl -s https://checkip.amazonaws.com)" >> "$GITHUB_ENV"

    - name: Setup MongoDB Atlas CLI
      uses: mongodb/atlas-github-action@v0.2.0
      with:
        username: ${{ secrets.ATLAS_PUBLIC_KEY }}
        password: ${{ secrets.ATLAS_PRIVATE_KEY }}

    - name: Add runner IP to MongoDB access list
      shell: bash
      run: |
        atlas accessLists create ${{ env.ip_address }} --type ipAddress --projectId ${{ secrets.MONGODB_PROJECT_ID }} --comment "Temporary access for GH Action"

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'node'

    - name: Install dependencies
      run: npm install

    - name: Run scraping script
      run: npm run scrapeRecent
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}

    - name: Remove runner IP from MongoDB access list
      shell: bash
      run: |
        atlas accessLists delete ${{ env.ip_address }} --projectId ${{ secrets.MONGODB_PROJECT_ID }} --force
